version: '3.7'

services:
  simple_sso:
    image: 'node:18-alpine'
    container_name: 'simple_sso'
    command: sh -c "yarn && yarn development"
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /simple_sso
    volumes:
      - ./:/simple_sso
    environment:
      - .env